networks:
  default:
    driver: bridge
services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      default:
        aliases:
        - localhost
    working_dir: /app
  frontend:
    build: ./frontend
    command: npx vite --host
    working_dir: /app
  nginx:
    depends_on:
    - backend
    - frontend
    image: nginx:alpine
    ports:
    - 3100:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
version: '3'
