# Generated by Django 5.2.3 on 2025-06-15 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodeploy.group')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(upload_to='archives/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('backend_port', models.IntegerField(blank=True, null=True)),
                ('frontend_port', models.IntegerField(blank=True, null=True)),
                ('backend_url', models.URLField(blank=True, null=True)),
                ('frontend_url', models.URLField(blank=True, null=True)),
                ('container_id_backend', models.CharField(blank=True, max_length=128, null=True)),
                ('container_id_frontend', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(default='uploaded', max_length=32)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodeploy.student')),
            ],
        ),
    ]
